In [1]:
# importando bibliotecas
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount ('/drive')

Mounted at /drive


In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [6]:
# abrindo arquivo csv e salvando em uma variável
df = pd.read_csv('/drive/MyDrive/sifilis_congenita.csv')
df.head(10)

<ipython-input-6-908b0e914473>:2: DtypeWarning: Columns (8,15,18,28,55,56,57,58,59,60,61,62) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/drive/MyDrive/sifilis_congenita.csv')


Unnamed: 0  TP_NOT  SEM_NOT ID_AGRAVO  DT_NOTIFIC  NU_ANO  SG_UF_NOT  \
0         263       2   201303      A509    20130118    2013         35   
1        4694       2   201319      A509    20130506    2013         35   
2        4712       2   201318      A509    20130430    2013         35   
3        4732       2   201318      A509    20130429    2013         35   
4        4720       2   201318      A509    20130503    2013         35   
5        4718       2   201318      A509    20130502    2013         35   
6        4717       2   201318      A509    20130502    2013         35   
7        4715       2   201318      A509    20130501    2013         35   
8        4738       2   201318      A509    20130429    2013         35   
9        4642       2   201318      A509    20130428    2013         35   

   ID_MUNICIP ID_REGIONA   DT_DIAG SEM_DIAG  NU_IDADE_N CS_SEXO CS_GESTANT  \
0      355030       1331  20121211                 2000       I              
1      351630       1334  20130427                 2000       M          6   
2      355030       1331  20130428                 2000       F          6   
3      351570       1333  20130429                 2002       M          6   
4      355030       1331  20130428                 2000       M          6   
5      355030       1331  20130428                 2000       M          6   
6      355030       1331  20130428                 2000       F          6   
7      355030       1331  20130428                 2001       F          6   
8      350600       1340  20130429                 2004       F          6   
9      355030       1331  20130426                 2000       F          6   

  CS_RACA CS_ESCOL_N  SG_UF  ID_MN_RESI ID_RG_RESI  ID_PAIS ANT_IDADE  \
0       9         10     35      355030   1331            1        26   
1       4         10     35      351630   1334            1        20   
2       1         10     35      355030   1331            1        17   
3       4         10     35      353980   1333            1        24   
4       1         10     35      355030   1331            1        42   
5       4         10     35      355030   1331            1        18   
6       4         10     35      355030   1331            1        26   
7       4         10     35      355030   1331            1        33   
8       4         10     35      350600   1340            1        17   
9       1         10     35      355030   1331            1        25   

   ANT_RACA ID_OCUPA_N  ESCOLMAE  ANT_PRE_NA UF_PRE_NAT MUN_PRE_NA  \
0         9                    9           2                         
1         4                    6           9                         
2         1                    9           1         SP     355030   
3         4                    9           1         SP     355030   
4         1                    9           1         SP     355030   
5         4                    3           1         SP     355030   
6         2                    5           1         SP     355030   
7         4                    3           2                         
8         4                    1           1         SP     350600   
9         1                    9           2                         

   ANTSIFIL_N LAB_PARTO LAB_TITU_2   LAB_DT3  LAB_CONF  TRA_ESQUEM    TRA_DT  \
0           2         2       ****  20121211         1           3  ********   
1           9         9       ****  ********         1           9  ********   
2           1         1          4  20130428         1           2  20121030   
3           1         2       ****  20130429         1           2  20130320   
4           2         1         16  20130428         3           3  ********   
5           1         1         64  20130428         3           2  20120915   
6           1         1          8  20130428         2           1  20130218   
7           2         1         64  20130428         3           3  ********   
8           1         1

In [7]:
df.columns

Index(['Unnamed: 0', 'TP_NOT', 'SEM_NOT', 'ID_AGRAVO', 'DT_NOTIFIC', 'NU_ANO',
       'SG_UF_NOT', 'ID_MUNICIP', 'ID_REGIONA', 'DT_DIAG', 'SEM_DIAG',
       'NU_IDADE_N', 'CS_SEXO', 'CS_GESTANT', 'CS_RACA', 'CS_ESCOL_N', 'SG_UF',
       'ID_MN_RESI', 'ID_RG_RESI', 'ID_PAIS', 'ANT_IDADE', 'ANT_RACA',
       'ID_OCUPA_N', 'ESCOLMAE', 'ANT_PRE_NA', 'UF_PRE_NAT', 'MUN_PRE_NA',
       'ANTSIFIL_N', 'LAB_PARTO', 'LAB_TITU_2', 'LAB_DT3', 'LAB_CONF',
       'TRA_ESQUEM', 'TRA_DT', 'ANT_TRATAD', 'ANT_UF_CRI', 'ANT_MUNI_C',
       'LABC_SANGU', 'LABC_TIT_1', 'LABC_DT_1', 'LABC_IGG', 'LABC_DT',
       'LABC_LIQUO', 'LABC_TIT_2', 'LABC_DT_2', 'LABC_TITUL', 'LABC_EVIDE',
       'LABC_LIQ_1', 'TRA_DIAG_T', 'TRA_ESQU_1', 'DS_ESQUEMA', 'EVOLUCAO',
       'DT_OBITO', 'EVO_DIAG_N', 'TRA_DIAG_C', 'CLI_ICTERI', 'CLI_RINITE',
       'CLI_ANEMIA', 'CLI_ESPLEN', 'HEPATO', 'CLI_OSTEO', 'LESOES',
       'CLI_OUTRO', 'SIN_OUTR_E', 'CLI_PSEUDO'],
      dtype='object')

In [8]:
df = df[['DT_NOTIFIC', 'NU_ANO', 'NU_IDADE_N', 'CS_SEXO', 'CS_RACA', 'ID_MN_RESI',
           'ANT_IDADE','ANT_RACA', 'ESCOLMAE', 'ANT_PRE_NA', 'ANTSIFIL_N',
           'LAB_PARTO', 'LAB_CONF', 'TRA_ESQUEM', 'ANT_TRATAD','LABC_SANGU',
           'LABC_LIQUO', 'LABC_TITUL', 'LABC_EVIDE', 'LABC_LIQ_1', 'TRA_DIAG_T',
           'CLI_ICTERI', 'CLI_RINITE', 'CLI_ANEMIA', 'CLI_ESPLEN', 'HEPATO',
           'CLI_OSTEO', 'LESOES', 'CLI_PSEUDO', 'CLI_OUTRO','TRA_ESQU_1',
           'EVOLUCAO', 'EVO_DIAG_N']]

# removi as colunas ID_OCUPA_N e TRA_DIAG_C (que seriam interessantes para análise) por conterem apenas NaN.
# mantive a coluna NU_ANO por facilitar o uso de group_by para análise descritiva (se for o caso)

In [9]:
df.head(10)

DT_NOTIFIC  NU_ANO  NU_IDADE_N CS_SEXO CS_RACA  ID_MN_RESI ANT_IDADE  \
0    20130118    2013        2000       I       9      355030        26   
1    20130506    2013        2000       M       4      351630        20   
2    20130430    2013        2000       F       1      355030        17   
3    20130429    2013        2002       M       4      353980        24   
4    20130503    2013        2000       M       1      355030        42   
5    20130502    2013        2000       M       4      355030        18   
6    20130502    2013        2000       F       4      355030        26   
7    20130501    2013        2001       F       4      355030        33   
8    20130429    2013        2004       F       4      350600        17   
9    20130428    2013        2000       F       1      355030        25   

   ANT_RACA  ESCOLMAE  ANT_PRE_NA  ANTSIFIL_N LAB_PARTO  LAB_CONF  TRA_ESQUEM  \
0         9         9           2           2         2         1           3   
1         4         6           9           9         9         1           9   
2         1         9           1           1         1         1           2   
3         4         9           1           1         2         1           2   
4         1         9           1           2         1         3           3   
5         4         3           1           1         1         3           2   
6         2         5           1           1         1         2           1   
7         4         3           2           2         1         3           3   
8         4         1           1           1         1         1           2   
9         1         9           2           2         1         1           3   

   ANT_TRATAD  LABC_SANGU  LABC_LIQUO  LABC_TITUL  LABC_EVIDE  LABC_LIQ_1  \
0           2           3           3           3           3           3   
1           9           1           2           9           9           1   
2           2           1           2           2           2           2   
3           2           9           9           9           9           9   
4           9           9           9           3           3           9   
5           2           1           2           2           2           2   
6           1           1           2           2           3           2   
7           9           1           2           9           3           2   
8           2           1           2           2           1           2   
9           2           1           2           3           3           2   

   TRA_DIAG_T CLI_ICTERI CLI_RINITE CLI_ANEMIA CLI_ESPLEN HEPATO CLI_OSTEO  \
0           3          3          3          3          3      3         3   
1           9          9          9          9          9      9         9   
2           2          2          2          2          2      2         2   
3           9          2          2          2          2      2         2   
4           2          2          2          2          2      2         2   
5           2          1          2          2          2      2         2   
6           2          2          2          2          2      2         2   
7           2          2          2          2          2      2         2   
8           2          2          2          2          2      2         2   
9           2          2          2          2          2      2         2   

  LESOES CLI_PSEUDO CLI_OUTRO  TRA_ESQU_1  EVOLUCAO  EVO_DIAG_N  
0      3          3         3           5         4           3  
1      9          9         9           9         1           1  
2      2          2         2           3         1           1  
3      2          2         2           1         9           1  
4      2          2         2           1         1           1  
5      2          2         2           1         1           1  
6      2          2         2           1         1           1  
7      2          2         2           1         

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36899 entries, 0 to 36898
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   DT_NOTIFIC  36899 non-null  int64 
 1   NU_ANO      36899 non-null  int64 
 2   NU_IDADE_N  36899 non-null  int64 
 3   CS_SEXO     36899 non-null  object
 4   CS_RACA     36899 non-null  object
 5   ID_MN_RESI  36899 non-null  int64 
 6   ANT_IDADE   36899 non-null  object
 7   ANT_RACA    36899 non-null  int64 
 8   ESCOLMAE    36899 non-null  int64 
 9   ANT_PRE_NA  36899 non-null  int64 
 10  ANTSIFIL_N  36899 non-null  int64 
 11  LAB_PARTO   36899 non-null  object
 12  LAB_CONF    36899 non-null  int64 
 13  TRA_ESQUEM  36899 non-null  int64 
 14  ANT_TRATAD  36899 non-null  int64 
 15  LABC_SANGU  36899 non-null  int64 
 16  LABC_LIQUO  36899 non-null  int64 
 17  LABC_TITUL  36899 non-null  int64 
 18  LABC_EVIDE  36899 non-null  int64 
 19  LABC_LIQ_1  36899 non-null  int64 
 20  TRA_DI

# Decodificando colunas com respostas iguais

### Conjunto 1

Colunas: LABC_TITUL, LABC_EVIDE, LABC_LIQ_1, TRA_DIAG_T,CLI_ICTERI, CLI_RINITE, CLI_ANEMIA, CLI_ESPLEN, HEPATO, CLI_OSTEO, LESOES, CLI_PSEUDO, CLI_OUTRO.


* 1 - sim
* 2 - não
* 3 - não se aplica
* 9 - ignorado.



In [11]:
conjunto_1 = ['LABC_TITUL', 'LABC_EVIDE', 'LABC_LIQ_1', 'TRA_DIAG_T',
              'CLI_ICTERI', 'CLI_RINITE','CLI_ANEMIA', 'CLI_ESPLEN',
              'HEPATO', 'CLI_OSTEO', 'LESOES', 'CLI_PSEUDO', 'CLI_OUTRO']

for item in conjunto_1:
      df[item] = pd.to_numeric(df[item], errors = 'coerce')

In [12]:
mapeamento_1 = {1 : 'Sim',
              2 : 'Não',
              3 : 'Não se aplica',
              9 : 'Ignorado'}

In [13]:
for coluna in conjunto_1:
    df[coluna] = df[coluna].map(lambda x: mapeamento_1.get(x, np.nan))

for coluna in conjunto_1:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

LABC_TITUL
['Não se aplica' 'Ignorado' 'Não' 'Sim']


LABC_EVIDE
['Não se aplica' 'Ignorado' 'Não' 'Sim']


LABC_LIQ_1
['Não se aplica' 'Sim' 'Não' 'Ignorado']


TRA_DIAG_T
['Não se aplica' 'Ignorado' 'Não' 'Sim']


CLI_ICTERI
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]


CLI_RINITE
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]


CLI_ANEMIA
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]


CLI_ESPLEN
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]


HEPATO
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]


CLI_OSTEO
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]


LESOES
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]


CLI_PSEUDO
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]


CLI_OUTRO
['Não se aplica' 'Ignorado' 'Não' 'Sim' nan]





### Conjunto 2

Colunas: LAB_PARTO, LAB_CONF, LABC_SANGU, LABC_LIQUO

* 1 – reagente
* 2 – não reagente
* 3 – não realizado
* 9 – ignorado.

In [14]:
conjunto_2 = ['LAB_PARTO', 'LAB_CONF', 'LABC_SANGU', 'LABC_LIQUO']

for item in conjunto_2:
      df[item] = pd.to_numeric(df[item], errors = 'coerce')

In [15]:
mapeamento_2 = {1 : 'Reagente',
              2 : 'Não reagente',
              3 : 'Não realizado',
              9 : 'Ignorado'}

In [16]:
for coluna in conjunto_2:
    df[coluna] = df[coluna].map(lambda x: mapeamento_2.get(x, np.nan))

for coluna in conjunto_2:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

LAB_PARTO
['Não reagente' 'Ignorado' 'Reagente' 'Não realizado' nan]


LAB_CONF
['Reagente' 'Não realizado' 'Não reagente' 'Ignorado']


LABC_SANGU
['Não realizado' 'Reagente' 'Ignorado' 'Não reagente']


LABC_LIQUO
['Não realizado' 'Não reagente' 'Ignorado' 'Reagente']





### Conjunto 3

Colunas: ANT_PRE_NA,  ANT_TRATAD

*   1 - sim
*   2 - não
*   9 - ignorado





In [17]:
conjunto_3 = ['ANT_PRE_NA', 'ANT_TRATAD']
# sem necessidade de converter em numérico, já reconhecido como 'int'

In [18]:
mapeamento_3 = {1 : 'Sim',
              2 : 'Não',
              9 : 'Ignorado'}

In [19]:
for coluna in conjunto_3:
    df[coluna] = df[coluna].map(lambda x: mapeamento_3.get(x, np.nan))

for coluna in conjunto_3:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

ANT_PRE_NA
['Não' 'Ignorado' 'Sim']


ANT_TRATAD
['Não' 'Ignorado' 'Sim']




### Conjunto 4

Colunas = CS_RACA, ANT_RACA

* 1 - Branca
* 2 - Preta,
* 3 - Amarela
* 4 - Parda
* 5- Indígena
* 9 - Ignorada

In [20]:
conjunto_4 = ['CS_RACA', 'ANT_RACA']

for item in conjunto_4:
      df[item] = pd.to_numeric(df[item], errors = 'coerce')

In [21]:
mapeamento_4 = {1 : 'Branca',
                2 : 'Preta',
                3 : 'Amarela',
                4 : 'Parda',
                5 : 'Indígena',
                9 : 'Ignorada'}

In [22]:
for coluna in conjunto_4:
    df[coluna] = df[coluna].map(lambda x: mapeamento_4.get(x, np.nan))

for coluna in conjunto_4:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

CS_RACA
['Ignorada' 'Parda' 'Branca' 'Preta' nan 'Indígena' 'Amarela']


ANT_RACA
['Ignorada' 'Parda' 'Branca' 'Preta' 'Amarela' 'Indígena']




# Tratando colunas individualmente

### Transformando a coluna DT_NOTIFIC no formato data

In [23]:
df['DT_NOTIFIC'] = pd.to_datetime(df['DT_NOTIFIC'], format = '%Y%m%d')

### Decodificando a coluna NU_IDADE_N
De acordo com o dicionário de variáveis: “A composição da variável obedece o seguinte critério: 1º dígito = 1. Hora , 2. Dia, 3. Mês, 4. Ano. Ex: 3009 — nove meses, 4018 — dezoito anos”.


In [24]:
df.NU_IDADE_N.unique()

array([2000, 2002, 2001, 2004, 2003, 2017, 2027, 3002, 2007, 2014, 2005,
       3003, 3001, 4001, 2028, 2006, 3004, 2024, 3011, 3000, 2013, 3007,
       2008, 2010, 2009, 2011, 2018, 2025, 2012, 2026, 3005, 2021, 3006,
       2019, 4003, 2015, 2016, 3009, 4006, 2030, 2022, 2020, 3010, 4004,
       3008, 4005, 4002, 2029, 2023, 4007, 4008])

In [25]:
df.NU_IDADE_N.value_counts()

NU_IDADE_N
2000    27867
2001     5948
2002     1359
2003      441
2004      193
3002      128
3001      119
2005      116
3003       92
2006       80
2007       57
4001       51
3004       41
2010       35
2008       32
2011       29
3005       25
2009       22
2013       20
3006       17
2014       16
4002       13
2016       13
2012       13
2028       11
2017       11
2015       11
3008       10
2020       10
2019       10
2018       10
3007       10
2021        9
2024        9
2022        8
2023        7
3009        7
2029        5
3010        5
2026        5
2030        5
2027        4
4004        4
3011        4
4003        4
2025        4
4007        3
4006        2
4005        2
3000        1
4008        1
Name: count, dtype: int64


**OBSERVAÇÃO**: Optamos em considerar valores = 2030 como 1 mês de vida e excluir valores = 3000.

In [26]:
remover_idade = df.loc[(df['NU_IDADE_N'] == 3000)]
df = df.drop(remover_idade.index)

In [27]:
idade = df['NU_IDADE_N']

def decode_idade(idade):
  if idade < 2030:
    return 'Menos de 1 mês'
  elif idade >= 2030 and idade <4000:
    return 'Entre 1 e 11 meses'
  elif idade >= 4000:
    return 'Mais de 1 ano'
  else:
    return np.NaN

df['NU_IDADE_N'] = list(map(decode_idade, idade))

In [28]:
df.NU_IDADE_N.unique()

array(['Menos de 1 mês', 'Entre 1 e 11 meses', 'Mais de 1 ano'],
      dtype=object)

In [29]:
df.NU_IDADE_N.value_counts()

NU_IDADE_N
Menos de 1 mês        36355
Entre 1 e 11 meses      463
Mais de 1 ano            80
Name: count, dtype: int64

### Decodificando a coluna CS_SEXO


* M - Masculino
* F - Feminino
* I - Ignorado



In [30]:
df['CS_SEXO'] = df['CS_SEXO'].map({'M' : 'Masculino',
                                   'F' : 'Feminino',
                                   'I' : 'Ignorado'})

In [31]:
df.CS_SEXO.value_counts()

CS_SEXO
Feminino     17322
Masculino    16457
Ignorado      3119
Name: count, dtype: int64

### Decodificando a coluna ESCOLMAE.
* 0 – analfabeta,
* 1 – 1ª a 4ª série incompleta do EF,
* 2 – até 4ª série completa do EF,
* 3 – 5 a 8ª série incompleta do EF,
* 4 – ensino fundamental completo,
* 5 – ensino médio incompleto,
* 6 – ensino médio completo,
* 7 – educação superior incompleta,
* 8 – educação superior completa,
* 9 – ignorada,
* 10 – não se aplica.

In [32]:
df.ESCOLMAE.unique()

array([ 9,  6,  3,  5,  1,  4, 10,  8,  0,  2,  7])

In [33]:
df['ESCOLMAE'] = df['ESCOLMAE'].map({0 : 'Analfabeta',
                                   1 : '1ª a 4ª série incompleta',
                                   2 : 'até 4ª série completa',
                                   3 : '5ª a 8ª série incompleta',
                                   4 : 'Ensino fundamental completo',
                                   5 : 'Ensino médio incompleto',
                                   6 : 'Ensino médio completo',
                                   7 : 'Educação superior incompleta',
                                   8 : 'Educação superior completa',
                                   9 : 'Ignorada',
                                   10 : 'Não se aplica'})

In [34]:
df.ESCOLMAE.value_counts()

ESCOLMAE
Ignorada                        10433
Ensino médio completo            8611
Ensino médio incompleto          5383
5ª a 8ª série incompleta         5208
Ensino fundamental completo      3969
1ª a 4ª série incompleta         1117
até 4ª série completa             808
Educação superior completa        498
Educação superior incompleta      471
Analfabeta                        210
Não se aplica                     190
Name: count, dtype: int64

### Decodificando a coluna ANTISIFIL_N.
1 - durante o pré-natal,
2 - no momento do parto/curetagem,
3 - após o parto,
4 - não realizado,
9 - ignorado.

In [35]:
df.ANTSIFIL_N.unique()

array([2, 9, 1, 4, 3])

In [36]:
df['ANTSIFIL_N'] = df['ANTSIFIL_N'].map({1 : 'Durante o pré-natal',
                                   2 : 'No momento do parto/curetagem',
                                   3 : 'Após o parto',
                                   4 : 'Não realizado',
                                   9 : 'Ignorado' })

In [37]:
df.ANTSIFIL_N.value_counts()

ANTSIFIL_N
Durante o pré-natal              22565
No momento do parto/curetagem    11952
Após o parto                      1276
Ignorado                           892
Não realizado                      213
Name: count, dtype: int64

### Decodificando a coluna TRA_ESQUEM.
1 - adequado,
2 - inadequado,
3 - não realizado,
9 - Ignorado

In [38]:
df.TRA_ESQUEM.unique()

array([3, 9, 2, 1])

In [39]:
df['TRA_ESQUEM'] = df['TRA_ESQUEM'].map({1 : 'Adequado',
                                   2 : 'Inadequado',
                                   3 : 'Não realizado',
                                   9 : 'Ignorado' })

In [40]:
df.TRA_ESQUEM.value_counts()

TRA_ESQUEM
Inadequado       18319
Não realizado    12495
Ignorado          3756
Adequado          2328
Name: count, dtype: int64

### Decodificando a coluna TRA_ESQU_1.
  1 - penicilina g cristalina 100.000 a 150.000 ui kg / dia / 10 dias,
  2 - penicilina g procaína 50.000 ui kg / dia / 10 dias,
  3 - penicilina g benzatina 50.000 ui kg / dia / dose única,
  4 - outro esquema,
  5 - não realizado,
  6 - não se aplica,
  9 - ignorado.

In [42]:
df.TRA_ESQU_1.unique()

array([5, 9, 3, 1, 4, 2])

In [43]:
df['TRA_ESQU_1'] = df['TRA_ESQU_1'].map({1 : 'Penicilina cristalina',
                                   2 : 'Penicilina procaína',
                                   3 : 'Penicilina benzatina',
                                   4 : 'Outro esquema',
                                   5 : 'Não realizado',
                                   6 : 'Não se aplica',
                                   9 : 'Ignorado' })

In [44]:
df.TRA_ESQU_1.value_counts()

TRA_ESQU_1
Penicilina cristalina    18522
Não realizado             4697
Penicilina benzatina      4669
Penicilina procaína       4626
Outro esquema             3219
Ignorado                  1165
Name: count, dtype: int64

### Decodificando a coluna EVOLUCAO.
1 - vivo, 2 - óbito por sífilis congênita, 3 - óbito por outras causas,  4 - aborto, 5 - natimorto, 9 - ignorado

In [45]:
df.EVOLUCAO.unique()

array([4, 1, 9, 5, 2, 3])

In [46]:
df['EVOLUCAO'] = df['EVOLUCAO'].map({1 : 'Vivo',
                                   2 : 'Óbito por sífilis congênita',
                                   3 : 'Óbito por outras causas',
                                   4 : 'Aborto',
                                   5 : 'Natimorto',
                                   9 : 'Ignorado' })

In [47]:
df.EVOLUCAO.value_counts()

EVOLUCAO
Vivo                           31797
Aborto                          2396
Natimorto                       1369
Ignorado                         592
Óbito por sífilis congênita      423
Óbito por outras causas          321
Name: count, dtype: int64

### Decodificando a coluna EVO_DIAG_N
1 - sífilis congênita recente,
2 - sífilis congênita tardia,
3 - aborto,
4 - natimorto,
5 - descartado.

In [48]:
df.EVO_DIAG_N.unique()

array([3, 1, 4, 2])

In [49]:
df['EVO_DIAG_N'] = df['EVO_DIAG_N'].map({1 : 'Sífilis congênita recente',
                                   2 : 'Sífilis congênita tardia',
                                   3 : 'Aborto',
                                   4 : 'Natimorto',
                                   5 : 'Descartado'})

In [50]:
df.EVO_DIAG_N.value_counts()

EVO_DIAG_N
Sífilis congênita recente    33103
Aborto                        2396
Natimorto                     1369
Sífilis congênita tardia        30
Name: count, dtype: int64

# Conferindo e salvando o dataframe no Drive

In [52]:
df.head(10)

DT_NOTIFIC  NU_ANO      NU_IDADE_N    CS_SEXO   CS_RACA  ID_MN_RESI  \
0 2013-01-18    2013  Menos de 1 mês   Ignorado  Ignorada      355030   
1 2013-05-06    2013  Menos de 1 mês  Masculino     Parda      351630   
2 2013-04-30    2013  Menos de 1 mês   Feminino    Branca      355030   
3 2013-04-29    2013  Menos de 1 mês  Masculino     Parda      353980   
4 2013-05-03    2013  Menos de 1 mês  Masculino    Branca      355030   
5 2013-05-02    2013  Menos de 1 mês  Masculino     Parda      355030   
6 2013-05-02    2013  Menos de 1 mês   Feminino     Parda      355030   
7 2013-05-01    2013  Menos de 1 mês   Feminino     Parda      355030   
8 2013-04-29    2013  Menos de 1 mês   Feminino     Parda      350600   
9 2013-04-28    2013  Menos de 1 mês   Feminino    Branca      355030   

  ANT_IDADE  ANT_RACA                  ESCOLMAE ANT_PRE_NA  \
0        26  Ignorada                  Ignorada        Não   
1        20     Parda     Ensino médio completo   Ignorado   
2        17    Branca                  Ignorada        Sim   
3        24     Parda                  Ignorada        Sim   
4        42    Branca                  Ignorada        Sim   
5        18     Parda  5ª a 8ª série incompleta        Sim   
6        26     Preta   Ensino médio incompleto        Sim   
7        33     Parda  5ª a 8ª série incompleta        Não   
8        17     Parda  1ª a 4ª série incompleta        Sim   
9        25    Branca                  Ignorada        Não   

                      ANTSIFIL_N     LAB_PARTO       LAB_CONF     TRA_ESQUEM  \
0  No momento do parto/curetagem  Não reagente       Reagente  Não realizado   
1                       Ignorado      Ignorado       Reagente       Ignorado   
2            Durante o pré-natal      Reagente       Reagente     Inadequado   
3            Durante o pré-natal  Não reagente       Reagente     Inadequado   
4  No momento do parto/curetagem      Reagente  Não realizado  Não realizado   
5            Durante o pré-natal      Reagente  Não realizado     Inadequado   
6            Durante o pré-natal      Reagente   Não reagente       Adequado   
7  No momento do parto/curetagem      Reagente  Não realizado  Não realizado   
8            Durante o pré-natal      Reagente       Reagente     Inadequado   
9  No momento do parto/curetagem      Reagente       Reagente  Não realizado   

  ANT_TRATAD     LABC_SANGU     LABC_LIQUO     LABC_TITUL     LABC_EVIDE  \
0        Não  Não realizado  Não realizado  Não se aplica  Não se aplica   
1   Ignorado       Reagente   Não reagente       Ignorado       Ignorado   
2        Não       Reagente   Não reagente            Não            Não   
3        Não       Ignorado       Ignorado       Ignorado       Ignorado   
4   Ignorado       Ignorado       Ignorado  Não se aplica  Não se aplica   
5        Não       Reagente   Não reagente            Não            Não   
6        Sim       Reagente   Não reagente            Não  Não se aplica   
7   Ignorado       Reagente   Não reagente       Ignorado  Não se aplica   
8        Não       Reagente   Não reagente            Não            Sim   
9        Não       Reagente   Não reagente  Não se aplica  Não se aplica   

      LABC_LIQ_1     TRA_DIAG_T     CLI_ICTERI     CLI_RINITE     CLI_ANEMIA  \
0  Não se aplica  Não se aplica  Não se aplica  Não se aplica  Não se aplica   
1            Sim       Ignorado       Ignorado       Ignorado       Ignorado   
2            Não            Não            Não            Não            Não   
3       Ignorado       Ignorado            Não            Não            Não   
4       Ignorado            Não            Não            Não            Não   
5            Não            Não            Sim            Não            Não   
6            Não            Não            Não            Não            Não   
7            Não            Não            Não            Não            Não   
8            Não            Não            Não            Não            Não 

In [53]:
from google.colab import drive
drive.mount ('/drive')
df.to_csv('/drive/MyDrive/sifilis_congenita_base_tratada.csv')

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).


### Decodificando a coluna ID_MN_RESI (pendente terminar, pode ficar em outro notebook se for fazer análise espacial da sífilis no estado de São Paulo).

In [ ]:
!pip install requests

In [ ]:
import requests

In [ ]:
dados_ibge_sp = 'https://servicodados.ibge.gov.br/api/v1/localidades/estados/35/municipios'

In [ ]:
request = requests.get(dados_ibge_sp)

In [ ]:
dados_municipios_sp = request.json()

In [ ]:
dados_municipios_sp

[{'id': 3500105,
  'nome': 'Adamantina',
  'microrregiao': {'id': 35035,
   'nome': 'Adamantina',
   'mesorregiao': {'id': 3508,
    'nome': 'Presidente Prudente',
    'UF': {'id': 35,
     'sigla': 'SP',
     'nome': 'São Paulo',
     'regiao': {'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}}}},
  'regiao-imediata': {'id': 350019,
   'nome': 'Adamantina - Lucélia',
   'regiao-intermediaria': {'id': 3505,
    'nome': 'Presidente Prudente',
    'UF': {'id': 35,
     'sigla': 'SP',
     'nome': 'São Paulo',
     'regiao': {'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}}}}},
 {'id': 3500204,
  'nome': 'Adolfo',
  'microrregiao': {'id': 35004,
   'nome': 'São José do Rio Preto',
   'mesorregiao': {'id': 3501,
    'nome': 'São José do Rio Preto',
    'UF': {'id': 35,
     'sigla': 'SP',
     'nome': 'São Paulo',
     'regiao': {'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}}}},
  'regiao-imediata': {'id': 350025,
   'nome': 'São José do Rio Preto',
   'regiao-intermediaria': {'id': 3507,
    'nome': 'S